import * as fs from "fs";
import * as path from "path";
import { ConversionResult } from "../converter/groq-converter";

export function writeYamlFiles(
  results: ConversionResult[],
  outputDir: string
): string[] {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const writtenFiles: string[] = [];

  results.forEach((result, i) => {
    const safeName = result.converted.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60);

    const fileName = `${String(i + 1).padStart(2, "0")}-${safeName}.yaml`;
    const filePath = path.join(outputDir, fileName);

    const header = `# Converted from: ${result.original.filePath}\n# Original test: "${result.original.name}"\n# Generated by PlayToMomentic\n\n`;
    fs.writeFileSync(filePath, header + result.yaml + "\n", "utf-8");
    writtenFiles.push(filePath);
  });

  // Also write a combined file
  const combinedPath = path.join(outputDir, "_all-tests.yaml");
  const combined = results
    .map((r, i) => `# --- Test ${i + 1}: ${r.converted.name} ---\n${r.yaml}`)
    .join("\n\n---\n\n");
  fs.writeFileSync(combinedPath, combined + "\n", "utf-8");
  writtenFiles.push(combinedPath);

  return writtenFiles;
}
